project_id = "ayplztujgpctozgmdxqy"

[functions.ai_generate_report]
verify_jwt = true

[functions.ai_skillscope]
verify_jwt = true

[functions.ai_needagentiq]
verify_jwt = false

[functions.ai_roi_brain]
verify_jwt = true

[functions.moneylost_compute]
verify_jwt = false

[functions.stripe_create_customer]
verify_jwt = true

[functions.stripe_checkout]
verify_jwt = true

[functions.stripe_webhooks]
verify_jwt = false